apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depolyment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.4
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgredata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgredata
        persistentVolumeClaim:
          claimName: postgres-pv-claim
